#!/bin/bash
set -o errexit  \
    -o nounset  \
    -o pipefail

function is_whitelisted()
{
  read -d '' -r PROGRAM <<'EOF' || true
    use strict;

    # Specifies the whitelist for each product / version / sub-product.
    # The sub-product is an optional string that contains a path. This
    # must be the top-level path from the version directory:
    #
    #   influxdb/1.9/Dockerfile             # -empty- sub-product
    #   influxdb/1.9/data/Dockerfile        # data    sub-product
    #   influxdb/1.9/data/alpine/Dockerfile # data    sub-product
    my %whitelist = (
      'influxdb' => [
        [ 1, 9, 'data' ],
        [ 1, 9, 'meta' ],
      ],
    );

    for my $line ( <STDIN> )
    {
      chomp ( $line );

      if ( $line !~
      /
        ^(.*?)\/          # product
         ([[:digit:]]+)\. # major version
         ([[:digit:]]+)   # minor version
         (?:\/(.*?))?     # sub-product
         \/Dockerfile$    # dockerfile
      /x )
      {
        next;
      }

      my $prod  = $1;
      my $major = $2;
      my $minor = $3;
      my $subp  = $4; $subp =~ s/\/alpine//;

      foreach my $element ( @{ $whitelist{$prod} } )
      {
        if ( @{ $element }[0] eq $major &&
             @{ $element }[1] eq $minor &&
             @{ $element }[2] eq $subp )
        {
          printf ( <<EOM
export PRODUCT=$prod
export VERSION_MAJOR=$major
export VERSION_MINOR=$minor
export SUBPRODUCT=$subp
EOM
          );

          exit 0;
        }
      }
    }

    printf ( <<EOM
export PRODUCT=
export VERSION_MAJOR=
export VERSION_MINOR=
export SUBPRODUCT=
EOM
    );
EOF
  # Analyses the paths that have changed between `HEAD~1` and `HEAD`
  # for whitelisted products and versions. This prevents circleci
  # from creating PRs in `official-images` for products that do
  # not officially use this release workflow.
  git diff --name-only HEAD~1..HEAD | perl -e "${PROGRAM}" 1>>"${BASH_ENV}"
}

is_whitelisted
