#!/bin/bash
set -eo pipefail

declare -r SCRIPT_DIR=$(cd $(dirname $0) >/dev/null 2>&1 && pwd)

declare -r TMP=${SCRIPT_DIR}/test-tmp
declare -r LOGS=${SCRIPT_DIR}/test-logs

#####################
##### UTILITIES #####
#####################

function log_msg () {
  echo "[$(date '+%Y/%m/%d %H:%M:%S %z')]" ${@}
}

function ensure_jq () {
    if ! which jq > /dev/null; then
        log_msg Error: 'jq' required to run tests
        exit 1
    fi
}

function tag_suffix () {
    if [ -n "$CIRCLE_BUILD_NUM" ]; then
        echo ${CIRCLE_BUILD_NUM}
    else
        date '+%Y-%m-%dT%H-%M-%S'
    fi
}

declare -r ATTEMPTS=30

function wait_for_log () {
    local attempt_count=0
    while [ ${attempt_count} -lt ${ATTEMPTS} ]; do
        if docker logs ${1} 2>&1 | grep -q "$2"; then
            return 0
        fi
        sleep 1
        attempt_count=$((attempt_count + 1))
    done
    log_msg Error: container ${1} did not start up in time
    return 1
}

function wait_for_startup () {
    wait_for_log $1 Listening
}

function wait_for_setup () {
    wait_for_log $1 "initialization complete"
}

function extract_token () {
    sed -En 's/^[[:space:]]+token[[:space:]]+=[[:space:]]+"([^"]+)"/\1/p' ${1}
}

function join_array () {
    local IFS=,
    echo "$*"
}

###########################
##### SETUP / CLEANUP #####
###########################

# Reuse a 1.x data zip from influxdb's tests to save time/effort.
declare -r INFLUXDB_1x_DATA_COMMIT=c62d3f2d8df917ce06741e98a72b7763fff875c8
declare -r INFLUXDB_1x_DATA_URL=https://github.com/influxdata/influxdb/raw/${INFLUXDB_1x_DATA_COMMIT}/cmd/influxd/upgrade/testdata/v1db.zip

function get_1x_data () {
    curl -sL -o ${TMP}/data.zip ${INFLUXDB_1x_DATA_URL}
    unzip -qq ${TMP}/data.zip -d ${TMP}
    rm ${TMP}/data.zip
}

function cleanup () {
    local -ra leftover_containers=($(docker ps -a -q -f name=*${suffix}))
    if [ ${#leftover_containers[@]} -gt 0 ]; then
        log_msg Cleaning up leftover containers...
        docker stop ${leftover_containers[@]}
        docker rm ${leftover_containers[@]}
    fi
    docker image rm -f influxdb:2.0-${1}
}

######################
##### TEST CASES #####
######################

declare -r TEST_USER=username
declare -r TEST_PASSWORD=password
declare -r TEST_ORG=org
declare -r TEST_BUCKET=bucket
declare -r TEST_RETENTION_SECONDS=604800

declare -r TEST_V1_DB=telegraf
declare -r TEST_V1_RP=autogen
declare -r TEST_V1_USER=v1-reader
declare -r TEST_V1_PASSWORD=v1-password
declare -r TEST_CREATE_DBRP_SCRIPT=$(cat <<EOF
#!/bin/bash
set -e

influx v1 dbrp create \
  --bucket-id \$INFLUXDB_INIT_BUCKET_ID \
  --db ${TEST_V1_DB} \
  --rp ${TEST_V1_RP} \
  --default \
  --org \$INFLUXDB_INIT_ORG
EOF
)
declare -r TEST_CREATE_V1_AUTH_SCRIPT=$(cat <<EOF
#!/bin/bash
set -e

influx v1 auth create \
  --username ${TEST_V1_USER} \
  --password ${TEST_V1_PASSWORD} \
  --read-bucket \$INFLUXDB_INIT_BUCKET_ID \
  --org \$INFLUXDB_INIT_ORG
EOF
)

function test_2x_simple_boot () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    local -ra docker_run_influxd=(
        docker run -i -d
        --name=${container_name}
        -u $(id -u):influxdb
        -p 8086:8086
        -v ${data}:/var/lib/influxdb2
        -v ${config}:/etc/influxdb2
        influxdb:${tag}
    )

    # First, run the container against the empty data dir.
    log_msg Booting 2.x container with no setup logic
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: Failed to launch container
        return 1
    fi
    wait_for_startup ${container_name}

    # Make sure the DB reports that it hasn't been set up yet.
    log_msg Checking onboarding API pre-setup
    local onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)

    if [[ ${onboarding_allowed} != 'true' ]]; then
        log_msg Error: Onboarding not allowed pre-setup
        return 1
    fi

    # Use the influx CLI to set up the DB.
    log_msg Running manual setup
    if ! docker exec -i ${container_name} influx setup -f \
        --username ${TEST_USER} \
        --password ${TEST_PASSWORD} \
        --org ${TEST_ORG} \
        --bucket ${TEST_BUCKET}; then
        log_msg Error: failed to run 'influx setup' command
        return 1
    fi

    # Make sure the DB reports that it's been set up.
    log_msg Checking onboarding API post-setup
    onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)

    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed post-setup
        return 1
    fi

    # Hack the auth token out of the CLI configs generated by setup.
    local -r auth_token=$(extract_token ${config}/influx-configs)

    # Make sure we can use the generated auth token to find the resources we expect.
    log_msg Checking org list post-setup
    local orgs=$(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/orgs | jq -r .orgs[].name)
    if [[ ${orgs} != ${TEST_ORG} ]]; then
        log_msg Error: Bad org list post-setup
        echo ${orgs}
        return 1
    fi

    log_msg Checking bucket list post-setup
    local buckets=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].name)
    if [[ ${buckets} != ${TEST_BUCKET} ]]; then
        log_msg Error: Bad bucket list post-setup
        echo ${buckets}
        return 1
    fi

    # Destroy the container
    log_msg Tearing down 2.x container
    docker stop ${container_name} > /dev/null
    docker logs ${container_name} > ${logs}/init-docker-stdout.log 2> ${logs}/init-docker-stderr.log
    docker rm ${container_name} > /dev/null

    # Check that files were persisted to the host.
    if [ ! -f ${data}/influxd.bolt ]; then
        log_msg Error: BoltDB not persisted to host directory
        return 1
    fi
    if [ ! -f ${config}/influx-configs ]; then
        log_msg Error: CLI configs not persisted to host directory
        return 1
    fi

    # Create a new container using the same mount-points.
    log_msg Booting another 2.x container
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: failed to launch container
        return 1
    fi
    wait_for_startup ${container_name}

    # Make sure the DB still reports that it's been set up.
    log_msg Checking onboarding API after recreating container
    onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)

    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed after recreating container
        return 1
    fi

    # Make sure we can still use the generated auth token to find the resources we expect.
    log_msg Checking org list after recreating container
    local orgs=$(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/orgs | jq -r .orgs[].name)
    if [[ ${orgs} != ${TEST_ORG} ]]; then
        log_msg Error: Bad org list post-setup
        echo ${orgs}
        return 1
    fi

    log_msg Checking bucket list after recreating container
    local buckets=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].name)
    if [[ ${buckets} != ${TEST_BUCKET} ]]; then
        log_msg Error: Bad bucket list post-setup
        echo ${buckets}
        return 1
    fi
}

function test_2x_custom_config () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    # Extract the default config from the container.
    log_msg Getting default config
    if ! docker run --rm influxdb:${tag} influxd print-config > ${config}/default-config.yml; then
        log_msg Error: Failed to extract default config
        return 1
    fi

    # Rewrite data paths.
    sed 's#/var/lib/influxdb2#/home/influxdb/influxdb2#g' ${config}/default-config.yml > ${config}/config.yml

    local -ra docker_run_influxd=(
        docker run -i -d
        --name=${container_name}
        -u $(id -u):influxdb
        -p 8086:8086
        -v ${data}:/home/influxdb/influxdb2
        -v ${config}:/etc/influxdb2
        influxdb:${tag}
    )

    log_msg Booting 2.x container with custom config
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: Failed to launch container
        return 1
    fi
    wait_for_startup ${container_name}

    log_msg Setting up DB with custom config
    if ! docker exec -i ${container_name} influx setup -f \
        --username ${TEST_USER} \
        --password ${TEST_PASSWORD} \
        --org ${TEST_ORG} \
        --bucket ${TEST_BUCKET}; then
        log_msg Error: failed to run 'influx setup' command
        return 1
    fi

    log_msg Tearing down 2.x container
    docker stop ${container_name} > /dev/null
    docker logs ${container_name} > ${logs}/init-docker-stdout.log 2> ${logs}/init-docker-stderr.log
    docker rm ${container_name} > /dev/null

    # Check that files were persisted to the host.
    if [ ! -f ${data}/influxd.bolt ]; then
        log_msg Error: BoltDB not persisted to host directory
        return 1
    fi

    # Create a new container using the same mount-points.
    log_msg Booting another 2.x container
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: failed to launch container
        return 1
    fi
    wait_for_startup ${container_name}

    # Make sure the DB still reports that it's been set up.
    log_msg Checking onboarding API after recreating container
    onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)

    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed after recreating container
        return 1
    fi
}

function test_2x_auto_setup_no_rp () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    local -ra docker_run_influxd=(
        docker run -i -d
        --name=${container_name}
        -u $(id -u):influxdb
        -p 8086:8086
        -v ${data}:/var/lib/influxdb2
        -v ${config}:/etc/influxdb2
        -e INFLUXDB_INIT_MODE=setup
        -e INFLUXDB_INIT_USERNAME=${TEST_USER}
        -e INFLUXDB_INIT_PASSWORD=${TEST_PASSWORD}
        -e INFLUXDB_INIT_ORG=${TEST_ORG}
        -e INFLUXDB_INIT_BUCKET=${TEST_BUCKET}
        influxdb:${tag}
    )

    log_msg Booting 2.x container in setup mode
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: Failed to launch container
        return 1
    fi
    wait_for_setup ${container_name}

    # Check that the DB reports it's been set up.
    log_msg Checking onboarding API post-start
    local onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)
    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed post-start
        return 1
    fi

    # Hack the auth token out of the CLI configs generated by setup.
    local -r auth_token=$(extract_token ${config}/influx-configs)

    # Make sure we can use the generated auth token to find the resources we expect.
    log_msg Checking org list post-setup
    local orgs=$(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/orgs | jq -r .orgs[].name)
    if [[ ${orgs} != ${TEST_ORG} ]]; then
        log_msg Error: Bad org list post-setup
        echo ${orgs}
        return 1
    fi

    log_msg Checking bucket list post-setup
    local buckets=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].name)
    if [[ ${buckets} != ${TEST_BUCKET} ]]; then
        log_msg Error: Bad bucket list post-setup
        echo ${buckets}
        return 1
    fi

    # Destroy the container
    log_msg Tearing down 2.x container
    docker stop ${container_name} > /dev/null
    docker logs ${container_name} > ${logs}/init-docker-stdout.log 2> ${logs}/init-docker-stderr.log
    docker rm ${container_name} > /dev/null

    # Check that files were persisted to the host.
    if [ ! -f ${data}/influxd.bolt ]; then
        log_msg Error: BoltDB not persisted to host directory
        return 1
    fi
    if [ ! -f ${config}/influx-configs ]; then
        log_msg Error: CLI configs not persisted to host directory
        return 1
    fi

    # Create a new container using the same mount-points and env.
    # The INIT_MODE should be ignored since the bolt file is present.
    log_msg Booting another 2.x container
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: failed to launch container
        return 1
    fi
    wait_for_startup ${container_name}

    # Make sure the DB still reports that it's been set up.
    log_msg Checking onboarding API after recreating container
    onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)

    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed after recreating container
        return 1
    fi

    # Make sure we can still use the generated auth token to find the resources we expect.
    log_msg Checking org list after recreating container
    local orgs=$(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/orgs | jq -r .orgs[].name)
    if [[ ${orgs} != ${TEST_ORG} ]]; then
        log_msg Error: Bad org list post-setup
        echo ${orgs}
        return 1
    fi

    log_msg Checking bucket list after recreating container
    local buckets=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].name)
    if [[ ${buckets} != ${TEST_BUCKET} ]]; then
        log_msg Error: Bad bucket list post-setup
        echo ${buckets}
        return 1
    fi
}

function test_2x_auto_setup_with_rp () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    local -ra docker_run_influxd=(
        docker run -i -d
        --name=${container_name}
        -u $(id -u):influxdb
        -p 8086:8086
        -v ${data}:/var/lib/influxdb2
        -v ${config}:/etc/influxdb2
        -e INFLUXDB_INIT_MODE=setup
        -e INFLUXDB_INIT_USERNAME=${TEST_USER}
        -e INFLUXDB_INIT_PASSWORD=${TEST_PASSWORD}
        -e INFLUXDB_INIT_ORG=${TEST_ORG}
        -e INFLUXDB_INIT_BUCKET=${TEST_BUCKET}
        -e INFLUXDB_INIT_RETENTION=${TEST_RETENTION_SECONDS}s
        influxdb:${tag}
    )

    # Boot the container
    log_msg Booting 2.x container in setup mode
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: Failed to launch container
        return 1
    fi
    wait_for_setup ${container_name}

    # Hack the auth token out of the CLI configs generated by setup.
    local -r auth_token=$(extract_token ${config}/influx-configs)

    log_msg Checking bucket RP
    local rp=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].retentionRules[].everySeconds)

    if [[ ${rp} != ${TEST_RETENTION_SECONDS} ]]; then
        log_msg Error: Bad bucket RP post-setup
        echo ${rp}
        return 1
    fi
}

function test_2x_auto_setup_custom_config () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    # Extract the default config from the container.
    log_msg Getting default config
    if ! docker run --rm influxdb:${tag} influxd print-config > ${config}/default-config.yml; then
        log_msg Error: Failed to extract default config
        return 1
    fi

    # Rewrite data paths.
    sed 's#/var/lib/influxdb2#/home/influxdb/influxdb2#g' ${config}/default-config.yml > ${config}/config.yml

    local -ra docker_run_influxd=(
        docker run -i -d
        --name=${container_name}
        -u $(id -u):influxdb
        -p 8086:8086
        -v ${data}:/home/influxdb/influxdb2
        -v ${config}:/etc/influxdb2
        -e INFLUXDB_INIT_MODE=setup
        -e INFLUXDB_INIT_USERNAME=${TEST_USER}
        -e INFLUXDB_INIT_PASSWORD=${TEST_PASSWORD}
        -e INFLUXDB_INIT_ORG=${TEST_ORG}
        -e INFLUXDB_INIT_BUCKET=${TEST_BUCKET}
        -e INFLUXDB_INIT_RETENTION=${TEST_RETENTION_SECONDS}s
        influxdb:${tag}
    )

    log_msg Booting 2.x container in setup mode
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: Failed to launch container
        return 1
    fi
    wait_for_setup ${container_name}

    # Check that the DB reports it's been set up.
    log_msg Checking onboarding API post-start
    local onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)
    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed post-start
        return 1
    fi

    # Hack the auth token out of the CLI configs generated by setup.
    local -r auth_token=$(extract_token ${config}/influx-configs)

    # Make sure we can use the generated auth token to find the resources we expect.
    log_msg Checking org list post-setup
    local orgs=$(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/orgs | jq -r .orgs[].name)
    if [[ ${orgs} != ${TEST_ORG} ]]; then
        log_msg Error: Bad org list post-setup
        echo ${orgs}
        return 1
    fi

    log_msg Checking bucket list post-setup
    local buckets=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].name)
    if [[ ${buckets} != ${TEST_BUCKET} ]]; then
        log_msg Error: Bad bucket list post-setup
        echo ${buckets}
        return 1
    fi

    log_msg Checking bucket RP
    local rp=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].retentionRules[].everySeconds)

    if [[ ${rp} != ${TEST_RETENTION_SECONDS} ]]; then
        log_msg Error: Bad bucket RP post-setup
        echo ${rp}
        return 1
    fi

    log_msg Tearing down 2.x container
    docker stop ${container_name} > /dev/null
    docker logs ${container_name} > ${logs}/init-docker-stdout.log 2> ${logs}/init-docker-stderr.log
    docker rm ${container_name} > /dev/null

    # Check that files were persisted to the host.
    if [ ! -f ${data}/influxd.bolt ]; then
        log_msg Error: BoltDB not persisted to host directory
        return 1
    fi

    # Create a new container using the same mount-points.
    log_msg Booting another 2.x container
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: failed to launch container
        return 1
    fi
    wait_for_startup ${container_name}

    # Make sure the DB still reports that it's been set up.
    log_msg Checking onboarding API after recreating container
    onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)

    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed after recreating container
        return 1
    fi

    log_msg Checking org list after recreating container
    local orgs=$(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/orgs | jq -r .orgs[].name)
    if [[ ${orgs} != ${TEST_ORG} ]]; then
        log_msg Error: Bad org list post-setup
        echo ${orgs}
        return 1
    fi

    log_msg Checking bucket list after recreating container
    local buckets=$(curl -s -H "Authorization: Token ${auth_token}" "localhost:8086/api/v2/buckets?name=${TEST_BUCKET}" | jq -r .buckets[].name)
    if [[ ${buckets} != ${TEST_BUCKET} ]]; then
        log_msg Error: Bad bucket list post-setup
        echo ${buckets}
        return 1
    fi
}

function test_2x_auto_setup_user_scripts () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5 scripts=$6

    echo "$TEST_CREATE_DBRP_SCRIPT" > ${scripts}/1-create-dbrp.sh
    echo "$TEST_CREATE_V1_AUTH_SCRIPT" > ${scripts}/2-create-v1-auth.sh
    chmod +x ${scripts}/1-create-dbrp.sh
    chmod +x ${scripts}/2-create-v1-auth.sh

    local -ra docker_run_influxd=(
        docker run -i -d
        --name=${container_name}
        -u $(id -u):influxdb
        -p 8086:8086
        -v ${data}:/var/lib/influxdb2
        -v ${config}:/etc/influxdb2
        -v ${scripts}:/docker-entrypoint-initdb.d
        -e INFLUXDB_INIT_MODE=setup
        -e INFLUXDB_INIT_USERNAME=${TEST_USER}
        -e INFLUXDB_INIT_PASSWORD=${TEST_PASSWORD}
        -e INFLUXDB_INIT_ORG=${TEST_ORG}
        -e INFLUXDB_INIT_BUCKET=${TEST_BUCKET}
        influxdb:${tag}
    )

    log_msg Booting 2.x container in setup mode
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: Failed to launch container
        return 1
    fi
    wait_for_setup ${container_name}

    log_msg Checking we can read from V1 API
    local -ra curl_v1=(
        curl -s
        -u ${TEST_V1_USER}:${TEST_V1_PASSWORD}
        --data-urlencode db=${TEST_V1_DB}
        --data-urlencode rp=${TEST_V1_RP}
        --data-urlencode q='SHOW MEASUREMENTS'
        localhost:8086/query
    )
    local -r measurements=$("${curl_v1[@]}" | jq -r .results[].statement_id)
    if [[ "${measurements}" != 0 ]]; then
        log_msg Got unexpected response from V1 API
        echo ${measurements}
        return 1
    fi
}

function test_2x_auto_upgrade () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    local -ra docker_run_influxd=(
        docker run -i -d
        --name=${container_name}
        -u $(id -u):influxdb
        -p 8086:8086
        -v ${data}:/var/lib/influxdb2
        -v ${config}:/etc/influxdb2
        -v ${TMP}/v1db:/var/lib/influxdb
        -e INFLUXDB_INIT_MODE=upgrade
        -e INFLUXDB_INIT_USERNAME=${TEST_USER}
        -e INFLUXDB_INIT_PASSWORD=${TEST_PASSWORD}
        -e INFLUXDB_INIT_ORG=${TEST_ORG}
        -e INFLUXDB_INIT_BUCKET=${TEST_BUCKET}
        -e INFLUXDB_INIT_RETENTION=${TEST_RETENTION_SECONDS}s
        influxdb:${tag}
    )

    log_msg Booting 2.x container in upgrade mode
    if ! ${docker_run_influxd[@]} > /dev/null; then
        log_msg Error: Failed to launch container
        return 1
    fi
    wait_for_setup ${container_name}

    log_msg Checking onboarding API post-upgrade
    local onboarding_allowed=$(curl -s localhost:8086/api/v2/setup | jq .allowed)
    if [[ ${onboarding_allowed} != 'false' ]]; then
        log_msg Error: Onboarding allowed post-upgrade
        return 1
    fi

    local -r auth_token=$(extract_token ${config}/influx-configs)

    log_msg Checking org list post-upgrade
    local orgs=$(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/orgs | jq -r .orgs[].name)
    if [[ ${orgs} != ${TEST_ORG} ]]; then
        log_msg Error: Bad org list post-setup
        echo ${orgs}
        return 1
    fi

    log_msg Checking bucket list post-upgrade
    local buckets=($(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/api/v2/buckets | jq -r .buckets[].name | sort))
    if [[ $(join_array ${buckets[@]}) != "_monitoring,_tasks,bucket,empty/autogen,mydb/1week,mydb/autogen,test/autogen" ]]; then
        log_msg Error: Bad bucket list post-upgrade
        echo ${buckets[@]}
        return 1
    fi

    log_msg Checking V1 user list post-upgrade
    local users=($(curl -s -H "Authorization: Token ${auth_token}" localhost:8086/private/legacy/authorizations | jq -r .authorizations[].token | sort))
    if [[ $(join_array ${users[@]}) != "reader,readerwriter,writer" ]]; then
        log_msg Error: Bad user list post-upgrade
        echo ${users[@]}
        return 1
    fi
}

function test_2x_auto_upgrade_custom_config () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    echo 'hola'
}

function test_2x_auto_upgrade_user_scripts () {
    local -r tag=$1 container_name=$2 data=$3 config=$4 logs=$5

    echo 'hola'
}

declare -ra TEST_CASES=(
    test_2x_simple_boot
    test_2x_custom_config
    test_2x_auto_setup_no_rp
    test_2x_auto_setup_with_rp
    test_2x_auto_setup_custom_config
    test_2x_auto_setup_user_scripts
    test_2x_auto_upgrade
    test_2x_auto_upgrade_custom_config
    test_2x_auto_upgrade_user_scripts
)

#######################
##### ENTRY-POINT #####
#######################

function main () {
    ensure_jq

    local -r suffix=$(tag_suffix)
    trap "cleanup ${suffix}" EXIT

    log_msg Building test image
    docker build -t influxdb:2.0-${suffix} ${SCRIPT_DIR}/2.0

    rm -rf ${TMP}
    mkdir -p ${TMP}

    log_msg Downloading 1.x data archive
    get_1x_data

    local -a failed_tests=()

    for tc in ${TEST_CASES[@]}; do
        if [[ $# > 0 && ${tc} != "$1" ]]; then
            continue
        fi

        # Define standard variables for the test case.
        local tag=2.0-${suffix}
        local container=${tc}_${suffix}
        local data=${TMP}/${tc}/data
        local config=${TMP}/${tc}/config
        local logs=${LOGS}/${tc}
        local scripts=${TMP}/${tc}/scripts

        mkdir -p ${data} ${config} ${logs} ${scripts}
        log_msg Running test ${tc}...
        set +e
        (set -eo pipefail; ${tc} ${tag} ${container} ${data} ${config} ${logs} ${scripts})
        local test_status=$?
        set -e
        if ((test_status)); then
            failed_tests+=(${tc})
            docker logs ${container} > ${logs}/docker-stdout.log 2> ${logs}/docker-stderr.log
        fi
        log_msg Cleaning up test ${tc}...
        docker stop ${container} >/dev/null && docker rm ${container} >/dev/null || true
    done

    if [ ${#failed_tests[@]} -eq 0 ]; then
        log_msg All tests succeeded
    else
        log_msg Some tests failed:
        for tc in ${failed_tests[@]}; do
            echo -e "\t${tc}"
        done
        exit 1
    fi
}

main ${@}
